import { cpSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { resolve, dirname, basename } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const src = resolve(root, 'node_modules/monaco-editor/min/vs');
const dest = resolve(root, 'src/templates/vendor/monaco/vs');

mkdirSync(dest, { recursive: true });
cpSync(src, dest, { recursive: true });

console.log('vendor: monaco-editor copied to src/templates/vendor/monaco/vs');

const themeSrc = resolve(root, 'node_modules/monaco-themes/themes');
const themeDest = resolve(root, 'src/templates/vendor/themes');

mkdirSync(themeDest, { recursive: true });

// Monaco requires theme names to match /^[a-zA-Z0-9\-_]+$/.
// Normalize: replace spaces with hyphens, strip all remaining illegal characters.
// Also skip themelist.json — it is an index file, not a theme definition.
const themes = {};
for (const file of readdirSync(themeSrc).filter((f) => f.endsWith('.json') && f !== 'themelist.json')) {
  const name = basename(file, '.json')
    .replace(/ /g, '-')
    .replace(/[^a-zA-Z0-9\-_]/g, '');
  themes[name] = JSON.parse(readFileSync(resolve(themeSrc, file), 'utf8'));
}

const output = `// Auto-generated by scripts/build-vendor.js — do not edit.\nwindow.__monacoThemes = ${JSON.stringify(themes, null, 2)};\n`;
writeFileSync(resolve(themeDest, 'themes.js'), output);

console.log(`vendor: ${Object.keys(themes).length} monaco-themes bundled to src/templates/vendor/themes/themes.js`);
